title: "AlgoWit"
url: https://www.markdownguide.org # site url
baseurl: "" # apply repo name if use it under gh-pages branch

repo: http://github.com/mattcone/markdown-guide
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap

collections:
  basic-syntax:
  extended-syntax:
  tutorials:
    output: true
    permalink: /tutorials/:title/
  tools:
    output: true
    permalink: /tools/:title/
  publications:
    output: true
    permalink: /publications/:title/


 
    

defaults:
  - scope:
      type: tools
    values:
      layout: tool
  - scope:
      type: tutorials
    values:
      layout: tutorial
  - scope:
      type: publications
    values:
      layout: publication
 

 
    

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name     : "AlgoWit"

# social settings
og_locale: "en_US"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile"]
